Directions/config/routes.rb
Directions::Application.routes.draw do
  root to: "directions#new"
  resources :directions
end

Directions/app/models/direction.rb
class Direction < ActiveRecord::Base
  require 'open-uri'
  require 'json'

  def turn_url_into_hash(url_string)
    url = URI.encode(url_string)
    string = open(url).read
    hash = JSON.parse(string)

    return hash
  end

  def google_directions
  hash = turn_url_into_hash("http://maps.googleapis.com/maps/api/geocode/json?address=#{self.start}&sensor=false")

  start_lat = hash["results"].first["geometry"]["location"]["lat"]
  start_long = hash["results"].first["geometry"]["location"]["lng"]

  start_cords = [start_lat, start_long]

  hash = turn_url_into_hash("http://maps.googleapis.com/maps/api/geocode/json?address=#{self.finish}&sensor=false")


  finish_lat = hash["results"].first["geometry"]["location"]["lat"]
  finish_long = hash["results"].first["geometry"]["location"]["lng"]

  finish_cords = [finish_lat, finish_long]

  directions_hash = turn_url_into_hash("http://maps.googleapis.com/maps/api/directions/json?origin=#{start_cords.first},#{start_cords.last}&destination=#{finish_cords.first},#{finish_cords.last}&mode=transit&departure_time=#{Time.now.to_i}&sensor=false")


    return directions_hash
  end

end

Directions/app/controllers/directions_controller.rb
class DirectionsController < ApplicationController
  before_action :set_direction, only: [:show, :edit, :update, :destroy]

  # GET /directions
  # GET /directions.json
  def index
    @directions = Direction.all
  end

  # GET /directions/1
  # GET /directions/1.json
  def show
    @directions_hash = @direction.google_directions
  end

  # GET /directions/new
  def new
    @direction = Direction.new
  end

  # GET /directions/1/edit
  def edit
  end

  # POST /directions
  # POST /directions.json
  def create
    @direction = Direction.new(direction_params)

    respond_to do |format|
      if @direction.save
        format.html { redirect_to @direction, notice: 'Direction was successfully created.' }
        format.json { render action: 'show', status: :created, location: @direction }
      else
        format.html { render action: 'new' }
        format.json { render json: @direction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /directions/1
  # PATCH/PUT /directions/1.json
  def update
    respond_to do |format|
      if @direction.update(direction_params)
        format.html { redirect_to @direction, notice: 'Direction was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @direction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /directions/1
  # DELETE /directions/1.json
  def destroy
    @direction.destroy
    respond_to do |format|
      format.html { redirect_to directions_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_direction
      @direction = Direction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def direction_params
      params.require(:direction).permit(:start, :finish)
    end
end

Directions/app/helpers/directions_helper.rb
module DirectionsHelper
end

Directions/app/views/directions/_form.html.erb
<%= form_for(@direction) do |f| %>
  <% if @direction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@direction.errors.count, "error") %> prohibited this direction from being saved:</h2>

      <ul>
      <% @direction.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :start %><br>
    <%= f.text_field :start %>
  </div>
  <div class="field">
    <%= f.label :finish %><br>
    <%= f.text_field :finish %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Directions/app/views/directions/edit.html.erb
<h1>Editing direction</h1>

<%= render 'form' %>

<%= link_to 'Show', @direction %> |
<%= link_to 'Back', directions_path %>

Directions/app/views/directions/index.html.erb
<h1>Listing directions</h1>

<table>
  <thead>
    <tr>
      <th>Start</th>
      <th>Finish</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @directions.each do |direction| %>
      <tr>
        <td><%= direction.start %></td>
        <td><%= direction.finish %></td>
        <td><%= link_to 'Show', direction %></td>
        <td><%= link_to 'Edit', edit_direction_path(direction) %></td>
        <td><%= link_to 'Destroy', direction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Direction', new_direction_path %>

Directions/app/views/directions/new.html.erb
<h1>New direction</h1>

<%= render 'form' %>

<%= link_to 'Back', directions_path %>

Directions/app/views/directions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Start:</strong>
  <%= @direction.start %>
</p>

<p>
  <strong>Finish:</strong>
  <%= @direction.finish %>
</p>

<%= @directions_hash %>

<%= link_to 'Edit', edit_direction_path(@direction) %> |
<%= link_to 'Back', directions_path %>

Directions/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Directions</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>